apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
  labels:
    istio.io/rev: 1-13
    app: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-az
  namespace: echoserver
  labels:
    app: echoserver-az
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver-az
  template:
    metadata:
      labels:
        app: echoserver-az
    spec:
      containers:
        - image: ealen/echo-server:latest
          imagePullPolicy: IfNotPresent
          name: echoserver
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: "COMMANDS__HTTPBODY__QUERY"
              value: "Hello from !!!!!AZURE!!!!!!"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-az
  namespace: echoserver
  labels:
    app: echoserver-az
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver-az
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: echoserver-az
  namespace: echoserver
spec:
  hosts:
    - echoserver.az.mesh.internal.com
  ports:
    - number: 80
      protocol: HTTP
      targetPort:
        number: 80
  services:
    - labels:
        app: echoserver-az
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: echoserver-east-west
  namespace: echoserver
spec:
  hosts:
    - "echoserver.echoserver.svc.cluster.local"
  workloadSelectors:
    - selector:
        labels:
          app: echoserver
  http:
    - name: echoserver
      matchers:
        - uri:
            prefix: /
      forwardTo:
        destinations:
          - ref:
              name: echoserver
            kind: VIRTUAL_DESTINATION
            port:
              number: 80
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: echoserver-az-east-west
  namespace: echoserver
spec:
  hosts:
    - "echoserver.az.mesh.internal.com"
  http:
    - name: echoserver-az
      matchers:
        - uri:
            prefix: /
      forwardTo:
        destinations:
          - ref:
              name: echoserver-az
              namespace: echoserver
              cluster: planetary-core-mesh-03
            kind: VIRTUAL_DESTINATION
            port:
              number: 80
