apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: echoserver-aws
  namespace: echoserver
spec:
  hosts:
    # Arbitrary, internal-only hostname assigned to the endpoint
    - echoserver.aws.mesh.internal.com
  ports:
    - number: 80
      protocol: HTTP
      targetPort:
        number: 80
  services:
    - labels:
        app: echoserver
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: echoserver-east-west
  namespace: echoserver
spec:
  hosts:
    - "echoserver.echoserver.svc.cluster.local"
  workloadSelectors:
    - selector:
        labels:
          app: echoserver
  http:
    - name: echoserver
      matchers:
        - uri:
            prefix: /
      forwardTo:
        destinations:
          - ref:
              name: echoserver
            kind: VIRTUAL_DESTINATION
            port:
              number: 80
