// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Planetwide.Members.Api.Infrastructure.Data;

#nullable disable

namespace Planetwide.Members.Api.Migrations
{
    [DbContext(typeof(MemberContext))]
    partial class MemberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Planetwide.Members.Api.Features.Members.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Planetwide.Members.Api.Features.Members.MemberMarketingPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ByEmail")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ByOnline")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ByPhone")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ByPost")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("BySmsMarketing")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("BySmsService")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ByTelephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FaceToFace")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("MemberMarketingPreferences");
                });

            modelBuilder.Entity("Planetwide.Members.Api.Features.Members.MemberMarketingPreferences", b =>
                {
                    b.HasOne("Planetwide.Members.Api.Features.Members.Member", "Member")
                        .WithOne("Preferences")
                        .HasForeignKey("Planetwide.Members.Api.Features.Members.MemberMarketingPreferences", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Planetwide.Members.Api.Features.Members.Member", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
