apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: north-south-gw
  namespace: istio-gateways
spec:
  workloads:
    - selector:
        labels:
          istio: ingressgateway
        cluster: planetary-core-mesh-01
  listeners: 
    - http: {}
      port:
        number: 80
      allowedRouteTables:
        - host: '*'
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: planetwide
  namespace: planetwide
  labels:
    expose: "true"
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: north-south-gw
      namespace: istio-gateways
      cluster: planetary-core-mesh-01
  workloadSelectors: []
  http:
    - name: planetwide
      matchers:
      - uri:
          prefix: /
      forwardTo:
        destinations:
          - ref:
              name: planetwide-gateway
              namespace: planetwide
            port:
              number: 80