services:
  ui:
    build:
      dockerfile: 'Planetwide.Blazor.Ui/Dockerfile'
      context: 'src/'
    environment:
      - Graphql:Gateway=http://localhost:9001/
    ports:
      - "8080:80"

  gateway:
    environment:
      - Graphql:Endpoint:Accounts=http://accounts.api/graphql/
      - Graphql:Endpoint:Members=http://members.api/graphql/
    build:
      dockerfile: 'Planetwide.Gateway/Dockerfile'
      context: 'src/'
    ports:
      - "9001:80"

  accounts.api:
    build:
      dockerfile: 'Planetwide.Accounts.Api/Dockerfile'
      context: 'src/'

  members.api:
    build:
      dockerfile: 'Planetwide.Members.Api/Dockerfile'
      context: 'src/'
