services:
  ui:
    build:
      dockerfile: 'Planetwide.Blazor.Ui/Dockerfile'
      context: 'src/'

  gateway:
    environment:
      - Graphql:Endpoint:Accounts=http://accounts.api/graphql/
      - Graphql:Endpoint:Members=http://members.api/graphql/
    build:
      dockerfile: 'Planetwide.Gateway/Dockerfile'
      context: 'src/'

  accounts.api:
    build:
      dockerfile: 'Planetwide.Accounts.Api/Dockerfile'
      context: 'src/'

  members.api:
    build:
      dockerfile: 'Planetwide.Members.Api/Dockerfile'
      context: 'src/'
