gloo:
  gatewayProxies:
    gatewayProxy:
      service:
        type: NodePort
        httpPort: 31000
        httpsPort: 31001
        httpNodePort: 31000
        httpsNodePort: 31001
gloo-fed:
  enabled: false
prometheus:
  enabled: false
grafana:
  defaultInstallationEnabled: false
global:
  glooMtls:
    sds:
      image:
        tag: 1.11.16
