services:
  gateway:
    container_name: planetwide-gateway-debug
    build:
      dockerfile: 'Planetwide.Gateway/Debug.Dockerfile'
      context: '.'
    volumes:
      - ./Planetwide.Gateway/bin/Debug/net6.0:/app

  accounts.api:
    container_name: planetwide-accounts-debug
    build:
      dockerfile: 'Planetwide.Accounts.Api/Debug.Dockerfile'
      context: '.'
    volumes:
      - ./Planetwide.Accounts.Api/bin/Debug/net6.0:/app
    ports:
      - "9002:80"

  members.api:
    container_name: planetwide-members-debug
    build:
      dockerfile: 'Planetwide.Members.Api/Debug.Dockerfile'
      context: '.'
    volumes:
      - ./Planetwide.Members.Api/bin/Debug/net6.0:/app
    ports:
      - "9003:80"

  transactions.api:
    container_name: planetwide-transactions-debug
    build:
      dockerfile: 'Planetwide.Transactions.Api/Debug.Dockerfile'
      context: '.'
    volumes:
      - ./Planetwide.Transactions.Api/bin/Debug/net6.0:/app
    ports:
      - "9004:80"

  redis:
    container_name: planetwide-redis-debug

  mongo:
    container_name: planetwide-mongo-debug

  zipkin:
    container_name: planetwide-zipkin-debug
