services:
  ui:
    build:
      dockerfile: 'Planetwide.Blazor.Ui/Dockerfile'
      context: '.'

  gateway:
    build:
      dockerfile: 'Planetwide.Gateway/Dockerfile'
      context: '.'

  accounts.api:
    build:
      dockerfile: 'Planetwide.Accounts.Api/Dockerfile'
      context: '.'

  members.api:
    build:
      dockerfile: 'Planetwide.Members.Api/Dockerfile'
      context: '.'

  transactions.api:
    build:
      dockerfile: 'Planetwide.Transactions.Api/Dockerfile'
      context: '.'
