apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: istio-system
  namespace: gloo-mesh
spec:
  workloadClusters:
    - name: planetary-core-mesh-01
      namespaces:
        - name: istio-system
        - name: istio-gateways
    - name: planetary-core-mesh-02
      namespaces:
        - name: istio-system
        - name: istio-gateways
    - name: planetary-core-mesh-03
      namespaces:
        - name: istio-system
        - name: istio-gateways

---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: planetwide
  namespace: gloo-mesh
spec:
  workloadClusters:
    - name: planetary-core-mesh-01
      namespaces:
        - name: planetwide
    - name: planetary-core-mesh-02
      namespaces:
        - name: echoserver
    - name: planetary-core-mesh-03
      namespaces:
        - name: echoserver
