apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: istio-system-settings
  namespace: istio-system
spec:
  importFrom:
    - workspaces:
        - name: planetwide
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: planetwide-settings
  namespace: planetwide
spec:
  exportTo:
    - workspaces:
        - name: istio-system
  options:
    serviceIsolation:
      enabled: false
    federation:
      enabled: true
      serviceSelector:
        - {}
      hostSuffix: "global"
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: echoserver-aws-east-west
  namespace: planetwide
spec:
  hosts:
    - "echoserver.aws.mesh.internal.com"
  http:
    - name: echoserver-aws
      matchers:
        - uri:
            prefix: /
      forwardTo:
        destinations:
          - ref:
              name: echoserver-aws
              namespace: echoserver
              cluster: planetary-core-mesh-02
            kind: VIRTUAL_DESTINATION
            port:
              number: 80
