gloo:
  gatewayProxies:
    gatewayProxy:
      service:
        type: NodePort
        httpPort: 31500
        httpsPort: 32500
        httpNodePort: 31500
        httpsNodePort: 32500
gloo-fed:
  enabled: false
prometheus:
  enabled: false
grafana:
  defaultInstallationEnabled: false
