kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31500
        hostPort: 31500
        protocol: TCP
      - containerPort: 32500
        hostPort: 32500
        protocol: TCP
